name: Update Packagist

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

permissions: {}

jobs:
  packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Packagist
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
          REPO_URL: https://github.com/${{ github.repository }}
        run: |
          curl --fail-with-body -s -X POST "https://packagist.org/api/update-package" \
            -d "{\"repository\":{\"url\":\"${REPO_URL}\"}}" \
            -H "Content-Type: application/json" \
            -u "${PACKAGIST_USERNAME}:${PACKAGIST_TOKEN}"
